#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WhatsUpdater.Resource", IsApplication=true)]

namespace WhatsUpdater
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int WhatsApp = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int buttonInstall = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int buttonRefresh = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int textViewHeader = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textViewInstalledVersion = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int textViewInstalledVersionLabel = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textViewLatestVersion = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int textViewLatestVersionLabel = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int appName = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int download = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int downloadFailed = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int header = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int install = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int labelInstallVersion = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int labelLatestVersion = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int noWifi = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int notFound = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int notInstalled = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int ok = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int oops = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int refresh = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int refreshMessage = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int requestFailed = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int startInstall = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
